const std = @import("std");

pub fn xapi_bindings(w: *std.Io.Writer) !void {
    // First we generate the header comment
    try w.writeAll("// This file is automatically generated\n\n");
    try w.writeAll("const rpc = struct {\n");
    try w.writeAll("    ");
    const rpc_s = @embedFile("./rpc.zig");
    for (rpc_s) |c| {
        try if (c == '\n') w.writeAll("\n    ") else w.writeByte(c);
    }
    try w.writeAll("\n};\n\n");
    try w.writeAll("// We want Conn to be visible from client, so we need to reexport it\n");
    try w.writeAll("pub const Conn = rpc.Connection;\n");
}
