const std = @import("std");
const RawXapi = @import("RawXapi.zig");

pub fn xapi_bindings(a: std.mem.Allocator, w: *std.Io.Writer, rapi: *const RawXapi) !void {
    var draft: std.Io.Writer.Allocating = .init(a);
    defer draft.deinit();

    const out = &draft.writer;

    // First we generate the header comment
    try out.writeAll("// This file is automatically generated\n");
    try out.print("const rpc = struct {{ {s} }};\n", .{@embedFile("rpc.zig")});
    try out.writeAll("// We want Conn to be visible from client, so we need to reexport it\n");
    try out.writeAll("pub const Conn = rpc.Connection;\n");

    // Starting struct Class
    try out.writeAll("pub const Class = struct {\n");

    for (rapi.root.items) |class_info| {
        const class_name: ClassName = .{ .raw = class_info.name };
        try out.print("pub const {f} = struct {{\n", .{class_name});
        // Only object classes (see hasRef) get a ref
        if (class_info.hasRef()) {
            try out.writeAll("ref: []const u8,\n");
            try out.print("pub const jsonParseFromValue = rpc.OpaqueRef({f}).jsonParseFromValue;\n", .{class_name});
        }
        try out.writeAll("};\n");
    }

    // End of pub const class
    try out.writeAll("};\n");

    // Now we can format "out" and print it in the writer.
    const source = try draft.toOwnedSliceSentinel(0);
    defer draft.allocator.free(source);

    var ast = try std.zig.Ast.parse(a, source, .zig);
    defer ast.deinit(a);

    if (ast.errors.len > 0) {
        for (ast.errors) |e| {
            const loc = ast.tokenLocation(0, e.token);
            var buf: [256]u8 = undefined;
            var msg: std.Io.Writer = .fixed(&buf);
            try ast.renderError(e, &msg);
            std.log.err("generated code {d}:{d}: {s}", .{ loc.line + 1, loc.column + 1, msg.buffered() });
        }
        return error.InvalidGeneratedCode;
    }

    return ast.render(a, w, .{});
}

const ClassName = struct {
    raw: []const u8,

    // ClassName is small so we can pass it by value
    pub fn format(self: ClassName, w: *std.Io.Writer) std.Io.Writer.Error!void {
        var it = std.mem.splitScalar(u8, self.raw, '_');
        while (it.next()) |s| {
            if (s.len == 0) continue;
            try w.writeByte(std.ascii.toUpper(s[0]));
            for (s[1..]) |c| {
                try w.writeByte(std.ascii.toLower(c));
            }
        }
    }
};

// Helper for tests
fn expectClassName(expected: []const u8, input: []const u8) !void {
    var buf: [64]u8 = undefined;
    var w: std.Io.Writer = .fixed(&buf);
    try w.print("{f}", .{ClassName{ .raw = input }});
    try std.testing.expectEqualStrings(expected, w.buffered());
}

test "class name conversion" {
    try expectClassName("Session", "session");
    try expectClassName("Vm", "VM");
    try expectClassName("VmGroup", "VM_group");
    try expectClassName("Vmpp", "VMPP");
    try expectClassName("SrStat", "sr_stat");
    try expectClassName("ClusterHost", "Cluster_host");
    try expectClassName("VdiNbdServerInfo", "vdi_nbd_server_info");
    // tricky cases not found in xenapi.json
    try expectClassName("AB", "a__b");
    try expectClassName("B", "b_");
    try expectClassName("B", "_b");
}
